// <auto-generated />
namespace Exwhyzee.Messaging.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userman : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userman));
        
        string IMigrationMetadata.Id
        {
            get { return "202103120807338_userman"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
