// <auto-generated />
namespace Exwhyzee.Messaging.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class apiupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(apiupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202309151605437_apiupdates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
